[project]
name = "semantic-release-template"
version = "0.1.0"
description = ""
authors = [
    {name = "IshaanJolly",email = "ijolly1997@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.semantic_release]
version_variable = "src/__init__.py:__version__"
commit_version_number = true  
upload_to_pypi = false        
upload_to_release = false    
commit_message = "chore(release): {version}"
