[tool.semantic_release]
version_variable = "src/__init__.py:__version__"
commit_version_number = true  
upload_to_pypi = false        
upload_to_release = true      
commit_message = "chore(release): {version}"