[tool.poetry]
name = "test"
version = "0.1.0"
description = "to create package with poety and semantic_release"
authors = ["Ishaan Jolly" <ijolly1997@gmail.com>]
readme = "README.md"

[tool.semantic_release]
version_variable = "src/your_package/__init__.py:__version__"
commit_version_number = true  
upload_to_pypi = false        
upload_to_release = true      
commit_message = "chore(release): {version}"